### ISSUE TITLE
Integration failed: libappimage not found, desktop integration is disabled

### ISSUE THREAD

**Issue by muralikodali** [DEVLOPRR/bread#1]
i  am using Arch linux. though libappimage (version 1.0.4-1) is installed , program is showing the following error.
```
Integration failed: libappimage not found, desktop integration is disabled
```
I would like to know where these appimage files are downloaded.

**Comment by DEVLOPRR** [comment]
What command did you run? Are you trying to build it yourself and then run?

**Comment by danrobi11** [comment]
>  would like to know where these appimage files are downloaded.

Ya same here. That info should be added in the readme.

**Comment by pegvin** [comment]
> I would like to know where these appimage files are downloaded.

You can now see the layout of Applications installed/run by bread: https://github.com/DEVLOPRR/bread#filefolder-layout

**Comment by muralikodali** [comment]
tried to add freetube

![screenshot_20220321114212](https://user-images.githubusercontent.com/11482766/159212879-03fc494b-2e04-4f31-bc9c-f37eebb765fe.png)

thanks for adding layout info in readme. 

I request you to give the ability to change the location of *Applications* folder.
one of the problems i am facing with appimages is their big download size, when compared to other installation methods. so, i try to download all the appimages to a different partition and launch applications using desktop files located in ~/.local/share/applications.

**Comment by pegvin** [comment]
Are you using the prebuilt binaries (Appimage from GitHub release) or compiling bread on your own system and then using it?

**Comment by muralikodali** [comment]
I am using prebuilt binary

**Comment by pegvin** [comment]
Check the latest Release, which contains better AppImage Detection & Some Other Functionalities Too

**Comment by pegvin** [comment]
The Latest binaries are now tested and are working successfully on Arch Linux!

**Comment by muralikodali** [comment]
thanks. 
bread is now working as intended on Arch Linux.
